from __future__ import annotations

ETF_METADATA = {
    "SPY": {"description": "SPDR S&P 500 ETF Trust", "category": "Benchmark"},
    "QQQ": {"description": "Invesco QQQ Trust", "category": "Benchmark"},
    "IWM": {"description": "iShares Russell 2000 ETF", "category": "Benchmark"},
    "DIA": {"description": "SPDR Dow Jones Industrial Average ETF Trust", "category": "Benchmark"},
    "VOO": {"description": "Vanguard S&P 500 ETF", "category": "Benchmark"},
    "VTI": {"description": "Vanguard Total Stock Market ETF", "category": "Benchmark"},
    "RSP": {"description": "Invesco S&P 500 Equal Weight ETF", "category": "Benchmark"},
    "TQQQ": {"description": "ProShares UltraPro QQQ", "category": "Leveraged"},
    "UPRO": {"description": "ProShares UltraPro S&P500", "category": "Leveraged"},
    "TNA": {"description": "Direxion Daily Small Cap Bull 3X Shares", "category": "Leveraged"},
    "XLF": {"description": "Financial Select Sector SPDR Fund", "category": "Sector"},
    "XLK": {"description": "Technology Select Sector SPDR Fund", "category": "Sector"},
    "XLE": {"description": "Energy Select Sector SPDR Fund", "category": "Sector"},
    "XLV": {"description": "Health Care Select Sector SPDR Fund", "category": "Sector"},
    "XLI": {"description": "Industrial Select Sector SPDR Fund", "category": "Sector"},
    "XLP": {"description": "Consumer Staples Select Sector SPDR Fund", "category": "Sector"},
    "XLY": {"description": "Consumer Discretionary Select Sector SPDR Fund", "category": "Sector"},
    "XLU": {"description": "Utilities Select Sector SPDR Fund", "category": "Sector"},
    "XLB": {"description": "Materials Select Sector SPDR Fund", "category": "Sector"},
    "XLRE": {"description": "Real Estate Select Sector SPDR Fund", "category": "Sector"},
    "XLC": {"description": "Communication Services Select Sector SPDR Fund", "category": "Sector"},
    "TLT": {"description": "iShares 20+ Year Treasury Bond ETF", "category": "Rates/Credit"},
    "LQD": {"description": "iShares iBoxx $ Investment Grade Corporate Bond ETF", "category": "Rates/Credit"},
    "HYG": {"description": "iShares iBoxx $ High Yield Corporate Bond ETF", "category": "Rates/Credit"},
    "USFR": {"description": "WisdomTree Floating Rate Treasury Fund", "category": "Rates/Credit"},
    "GLD": {"description": "SPDR Gold Shares", "category": "Commodities"},
    "SLV": {"description": "iShares Silver Trust", "category": "Commodities"},
    "USO": {"description": "United States Oil Fund", "category": "Commodities"},
    "UNG": {"description": "United States Natural Gas Fund", "category": "Commodities"},
    "EEM": {"description": "iShares MSCI Emerging Markets ETF", "category": "International"},
    "FXI": {"description": "iShares China Large-Cap ETF", "category": "International"},
    "ASHR": {"description": "Xtrackers Harvest CSI 300 China A-Shares ETF", "category": "International"},
    "EWG": {"description": "iShares MSCI Germany ETF", "category": "International"},
    "EWC": {"description": "iShares MSCI Canada ETF", "category": "International"},
    "FEZ": {"description": "SPDR EURO STOXX 50 ETF", "category": "International"},
    "SMH": {"description": "VanEck Semiconductor ETF", "category": "Thematic"},
    "XBI": {"description": "SPDR S&P Biotech ETF", "category": "Thematic"},
    "KRE": {"description": "SPDR S&P Regional Banking ETF", "category": "Thematic"},
    "ARKK": {"description": "ARK Innovation ETF", "category": "Thematic"},
    "JETS": {"description": "U.S. Global Jets ETF", "category": "Thematic"},
    "IYR": {"description": "iShares U.S. Real Estate ETF", "category": "Thematic"},
    "TAN": {"description": "Invesco Solar ETF", "category": "Thematic"},
    "URA": {"description": "Global X Uranium ETF", "category": "Thematic"},
    "URNM": {"description": "Sprott Uranium Miners ETF", "category": "Thematic"},
    "ICLN": {"description": "iShares Global Clean Energy ETF", "category": "Thematic"},
}


def get_metadata(ticker: str) -> dict[str, str]:
    return ETF_METADATA.get(ticker, {"description": ticker, "category": "Single Name"})
